#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build

echo bundle exec htmlproofer ./_site --url-swap ^/devguide: --url-ignore "/https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css/,/https://docs.ansible.com/ansible/2.4/ansible-playbook.html/,/https://plugins.jenkins.io/cloudshell-sandbox/,/https://support.quali.com/"
bundle exec htmlproofer ./_site --url-swap ^/devguide: --url-ignore "/https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css/,/https://docs.ansible.com/ansible/2.4/ansible-playbook.html/,/https://plugins.jenkins.io/cloudshell-sandbox/,/https://support.quali.com/"